name: Docker Image CI

on:
  push:
    branches: [master, image-push]
  pull_request:
    branches: [master, image-push]
  workflow_dispatch:


# permissions: 
#   packages: write

jobs:
  build:
    permissions:
      packages: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
